In [292]:
# !git clone https://github.com/hummingbot/hummingbot.git

In [293]:
# https://github.com/hummingbot/hummingbot/tree/master/hummingbot/strategy/avellaneda_market_making

In [294]:
import pandas as pd
import numpy as np

In [295]:
orderbook_df = pd.read_csv ('historical_ETHUSDT_orderbook_data.csv')

In [296]:
orderbook_df.head(50).loc[:, ["Datetime"] + ['bidp' + str(i) for i in range(10)] ]

,Datetime,bidp0,bidp1,bidp2,bidp3,bidp4,bidp5,bidp6,bidp7,bidp8,bidp9
0,1710470077221,3816.80,3816.79,3816.78,3816.76,3816.72,3816.70,3816.68,3816.67,3816.64,3816.63
1,1710470077337,3816.80,3816.79,3816.78,3816.76,3816.75,3816.74,3816.72,3816.70,3816.68,3816.67
2,1710470077476,3816.80,3816.79,3816.78,3816.76,3816.75,3816.72,3816.68,3816.67,3816.64,3816.63
3,1710470077584,3816.80,3816.79,3816.78,3816.76,3816.72,3816.68,3816.65,3816.64,3816.63,3816.62
4,1710470077711,3816.80,3816.79,3816.78,3816.76,3816.72,3816.68,3816.65,3816.64,3816.62,3816.60
5,1710470077818,3816.64,3816.62,3816.60,3816.59,3816.56,3816.55,3816.52,3816.50,3816.49,3816.48
6,1710470077920,3816.46,3816.44,3816.43,3816.42,3816.40,3816.39,3816.38,3816.36,3816.32,3816.28
7,1710470078022,3816.31,3816.26,3816.25,3816.20,3816.18,3816.16,3816.14,3816.11,3816.10,3816.09
8,1710470078125,3816.31,3816.30,3816.26,3816.25,3816.20,3816.19,3816.18,3816.14,3816.13,3816.11
9,1710470078257,3816.00,3815.99,3815.98,3815.96,3815.92,3815.89,3815.88,3815.87,3815.85,3815.84
10,1710470078359,3815.65,3815.64,3815.61,3815.60,3815.58,3815.56,3815.52,3815.50,3815.48,3815.47
11,1710470078462,3815.65,3815.64,3815.61,3815.60,3815.56,3815.52,3815.50,3815.48,3815.47,3815.44
12,1710470078572,3815.28,3815.24,3815.22,3815.20,3815.18,3815.16,3815.12,3815.11,3815.08,3815.04
13,1710470078678,3815.28,3815.24,3815.20,3815.18,3815.16,3815.14,3815.13,3815.12,3815.08,3815.04
14,1710470078786,3815.28,3815.27,3815.24,3815.20,3815.18,3815.16,3815.14,3815.13,3815.12,3815.08
15,1710470078894,3815.20,3815.18,3815.16,3815.12,3815.09,3815.08,3815.04,3815.02,3815.00,3814.99
16,1710470079008,3815.08,3815.07,3815.04,3815.02,3815.00,3814.96,3814.94,3814.93,3814.92,3814.90
17,1710470079122,3815.08,3815.07,3815.04,3815.02,3815.01,3815.00,3814.96,3814.94,3814.92,3814.90
18,1710470079230,3815.08,3815.07,3815.04,3815.02,3815.01,3815.00,3814.96,3814.94,3814.92,3814.90
19,1710470079333,3815.08,3815.07,3815.04,3815.02,3815.01,3815.00,3814.96,3814.94,3814.92,3814.90
20,1710470079447,3815.08,3815.07,3815.04,3815.02,3815.01,3815.00,3814.96,3814.94,3814.92,3814.90
21,1710470079630,3815.08,3815.07,3815.04,3815.02,3815.01,3815.00,3814.96,3814.94,3814.92,3814.90
22,1710470079729,3815.08,3815.07,3815.05,3815.04,3815.02,3815.00,3814.96,3814.94,3814.92,3814.90
23,1710470079905,3815.08,3815.07,3815.05,3815.04,3815.02,3815.00,3814.96,3814.94,3814.92,3814.90
24,1710470080066,3815.08,3815.07,3815.05,3815.04,3815.02,3815.00,3814.99,3814.96,3814.94,3814.92
25,1710470080205,3815.08,3815.07,3815.05,3815.04,3815.00,3814.99,3814.96,3814.94,3814.92,3814.90
26,1710470080315,3815.08,3815.07,3815.04,3815.00,3814.99,3814.96,3814.94,3814.93,3814.92,3814.90
27,1710470080429,3814.64,3814.61,3814.60,3814.59,3814.56,3814.50,3814.49,3814.47,3814.45,3814.43
28,1710470080537,3814.10,3814.09,3814.08,3814.07,3814.06,3814.05,3814.03,3814.00,3813.99,3813.98
29,1710470080645,3814.10,3814.09,3814.07,3814.06,3814.05,3814.03,3814.00,3813.99,3813.98,3813.97
30,1710470080754,3814.10,3814.09,3814.07,3814.06,3814.05,3814.03,3814.00,3813.99,3813.98,3813.97
31,1710470080862,3814.60,3814.59,3814.56,3814.54,3814.52,3814.45,3814.44,3814.40,3814.39,3814.38
32,1710470080964,3814.61,3814.60,3814.58,3814.56,3814.54,3814.52,3814.48,3814.45,3814.44,3814.40
33,1710470081072,3814.61,3814.60,3814.58,3814.56,3814.54,3814.52,3814.48,3814.45,3814.44,3814.40
34,1710470081175,3814.61,3814.60,3814.56,3814.54,3814.47,3814.44,3814.40,3814.39,3814.38,3814.37
35,1710470081282,3814.61,3814.60,3814.56,3814.54,3814.47,3814.44,3814.41,3814.40,3814.39,3814.38
36,1710470081392,3814.61,3814.60,3814.56,3814.54,3814.47,3814.44,3814.41,3814.40,3814.39,3814.38
37,1710470081524,3814.61,3814.44,3814.41,3814.40,3814.39,3814.38,3814.37,3814.36,3814.33,3814.31
38,1710470081650,3813.92,3813.90,3813.89,3813.84,3813.80,3813.79,3813.78,3813.76,3813.74,3813.72
39,1710470081752,3813.92,3813.90,3813.89,3813.84,3813.80,3813.79,3813.78,3813.76,3813.74,3813.72
40,1710470081897,3813.84,3813.79,3813.78,3813.76,3813.74,3813.72,3813.69,3813.68,3813.67,3813.65
41,1710470081983,3814.79,3814.77,3814.76,3814.75,3814.74,3814.73,3814.72,3814.71,3814.70,3814.59
42,1710470082111,3814.77,3814.76,3814.75,3814.74,3814.73,3814.72,3814.71,3814.70,3814.68,3814.64
43,1710470082217,3814.77,3814.76,3814.75,3814.72,3814.68,3814.64,3814.60,3814.56,3814.54,3814.53
44,1710470082341,3814.54,3814.52,3814.48,3814.44,3814.43,3814.40,3814.38,3814.37,3814.36,3814.33
45,1710470082491,3814.54,3814.52,3814.48,3814.44,3814.43,3814.40,3814.38,3814.37,3814.36,3814.33
46,1710470082596,3815.19,3815.15,3815.01,3815.00,3814.93,3814.88,3814.86,3814.84,3814.83,3814.80
47,1710470082698,3815.03,3815.00,3814.97,3814.88,3814.86,3814.84,3814.82,3814.76,3814.70,3814.69
48,1710470082804,3815.03,3814.97,3814.84,3814.82,3814.72,3814.70,3814.69,3814.64,3814.62,3814.61
49,1710470082914,3815.03,3814.97,3814.95,3814.84,3814.82,3814.76,3814.72,3814.70,3814.69,3814.64

In [297]:
orderbook_df.head(50).loc[:, ["Datetime"] + ['askp' + str(i) for i in range(10)] ]

,Datetime,askp0,askp1,askp2,askp3,askp4,askp5,askp6,askp7,askp8,askp9
0,1710470077221,3816.81,3816.82,3816.89,3816.91,3816.99,3817.02,3817.08,3817.09,3817.12,3817.14
1,1710470077337,3816.81,3816.82,3816.89,3816.91,3816.99,3817.02,3817.08,3817.09,3817.12,3817.14
2,1710470077476,3816.81,3816.82,3816.89,3816.91,3816.99,3817.00,3817.02,3817.08,3817.09,3817.10
3,1710470077584,3816.81,3816.82,3816.83,3816.84,3816.89,3816.91,3816.94,3816.99,3817.00,3817.02
4,1710470077711,3816.81,3816.82,3816.83,3816.84,3816.89,3816.91,3816.94,3816.99,3817.00,3817.02
5,1710470077818,3816.65,3816.66,3816.67,3816.69,3816.70,3816.72,3816.73,3816.74,3816.75,3816.77
6,1710470077920,3816.47,3816.48,3816.49,3816.53,3816.54,3816.57,3816.59,3816.60,3816.62,3816.63
7,1710470078022,3816.32,3816.43,3816.44,3816.46,3816.47,3816.51,3816.52,3816.53,3816.54,3816.57
8,1710470078125,3816.32,3816.35,3816.39,3816.43,3816.46,3816.47,3816.51,3816.52,3816.53,3816.54
9,1710470078257,3816.04,3816.05,3816.06,3816.07,3816.09,3816.10,3816.11,3816.12,3816.14,3816.15
10,1710470078359,3815.66,3815.67,3815.68,3815.69,3815.70,3815.71,3815.72,3815.74,3815.77,3815.80
11,1710470078462,3815.66,3815.67,3815.68,3815.69,3815.71,3815.72,3815.74,3815.77,3815.80,3815.83
12,1710470078572,3815.29,3815.32,3815.33,3815.36,3815.39,3815.40,3815.48,3815.50,3815.60,3815.62
13,1710470078678,3815.29,3815.36,3815.48,3815.50,3815.56,3815.60,3815.62,3815.65,3815.66,3815.68
14,1710470078786,3815.29,3815.30,3815.34,3815.36,3815.40,3815.48,3815.50,3815.56,3815.60,3815.62
15,1710470078894,3815.21,3815.22,3815.23,3815.24,3815.26,3815.28,3815.29,3815.34,3815.36,3815.40
16,1710470079008,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.23,3815.24,3815.26
17,1710470079122,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.23,3815.24,3815.26
18,1710470079230,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.24,3815.26,3815.29
19,1710470079333,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.24,3815.26,3815.29
20,1710470079447,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.24,3815.26,3815.29
21,1710470079630,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.24,3815.26,3815.29
22,1710470079729,3815.09,3815.10,3815.11,3815.12,3815.20,3815.21,3815.22,3815.24,3815.26,3815.29
23,1710470079905,3815.09,3815.10,3815.11,3815.12,3815.17,3815.20,3815.21,3815.22,3815.24,3815.26
24,1710470080066,3815.09,3815.10,3815.11,3815.12,3815.17,3815.20,3815.21,3815.22,3815.24,3815.26
25,1710470080205,3815.09,3815.10,3815.11,3815.12,3815.17,3815.18,3815.20,3815.21,3815.22,3815.24
26,1710470080315,3815.09,3815.10,3815.11,3815.12,3815.17,3815.18,3815.20,3815.21,3815.22,3815.24
27,1710470080429,3814.65,3814.66,3814.67,3814.68,3814.69,3814.70,3814.73,3814.75,3814.76,3814.77
28,1710470080537,3814.11,3814.14,3814.16,3814.17,3814.18,3814.20,3814.21,3814.22,3814.23,3814.24
29,1710470080645,3814.11,3814.14,3814.16,3814.18,3814.20,3814.21,3814.23,3814.28,3814.30,3814.31
30,1710470080754,3814.11,3814.16,3814.28,3814.30,3814.32,3814.33,3814.35,3814.36,3814.38,3814.39
31,1710470080862,3814.61,3814.62,3814.65,3814.66,3814.67,3814.76,3814.88,3814.90,3814.91,3814.99
32,1710470080964,3814.62,3814.65,3814.66,3814.67,3814.76,3814.80,3814.83,3814.88,3814.90,3814.91
33,1710470081072,3814.62,3814.65,3814.66,3814.67,3814.76,3814.80,3814.83,3814.88,3814.90,3814.91
34,1710470081175,3814.62,3814.64,3814.65,3814.66,3814.67,3814.70,3814.76,3814.80,3814.83,3814.86
35,1710470081282,3814.62,3814.64,3814.65,3814.66,3814.67,3814.70,3814.76,3814.77,3814.80,3814.83
36,1710470081392,3814.62,3814.64,3814.65,3814.66,3814.67,3814.70,3814.76,3814.77,3814.80,3814.83
37,1710470081524,3814.62,3814.64,3814.65,3814.66,3814.67,3814.70,3814.76,3814.77,3814.80,3814.83
38,1710470081650,3813.93,3813.94,3813.96,3813.97,3813.98,3814.00,3814.02,3814.04,3814.05,3814.06
39,1710470081752,3813.93,3813.94,3813.98,3814.00,3814.04,3814.05,3814.06,3814.07,3814.08,3814.10
40,1710470081897,3813.85,3813.90,3813.91,3813.92,3813.93,3813.94,3813.96,3813.98,3814.00,3814.01
41,1710470081983,3814.80,3814.82,3814.83,3814.85,3814.88,3814.90,3814.92,3814.93,3814.95,3814.99
42,1710470082111,3814.78,3814.79,3814.80,3814.84,3814.85,3814.86,3814.90,3814.91,3814.92,3814.93
43,1710470082217,3814.78,3814.79,3814.80,3814.84,3814.85,3814.86,3814.88,3814.90,3814.91,3814.92
44,1710470082341,3814.55,3814.57,3814.60,3814.61,3814.64,3814.70,3814.76,3814.77,3814.78,3814.79
45,1710470082491,3814.55,3814.64,3814.70,3814.76,3814.77,3814.78,3814.80,3814.84,3814.85,3814.86
46,1710470082596,3815.20,3815.23,3815.24,3815.28,3815.30,3815.32,3815.33,3815.34,3815.36,3815.39
47,1710470082698,3815.04,3815.08,3815.12,3815.13,3815.14,3815.18,3815.19,3815.20,3815.24,3815.28
48,1710470082804,3815.04,3815.08,3815.12,3815.13,3815.16,3815.18,3815.19,3815.20,3815.24,3815.28
49,1710470082914,3815.04,3815.05,3815.08,3815.12,3815.13,3815.16,3815.18,3815.19,3815.20,3815.22

In [298]:
# Trading intensity
# https://github.com/hummingbot/hummingbot/blob/master/hummingbot/strategy/__utils__/trailing_indicators/trading_intensity.pyx

from sklearn.linear_model import LinearRegression

def trading_intensity(time):
    end_time = time
    start_time = time - 60000 # 60000 = 1min, 1000 = 1sec
    
    sampling_df = orderbook_df[ ( orderbook_df['Datetime']>= start_time ) & ( orderbook_df['Datetime'] <= end_time ) ].reset_index()
    
    ask_order_price_trading_intensity = []
    bid_order_price_trading_intensity = []
    
    sampling_df = sampling_df[['Datetime','bidp0','askp0']]
    
    for index , row in sampling_df.iterrows():
        if index == 0:
            new_ask_order_indexes = []
            new_ask_order_datetimes = []
            new_ask_order_prices = []
            
            new_bid_order_indexes = []
            new_bid_order_datetimes = []
            new_bid_order_prices = []
            
            continue
            
        # collect ask orders
            
        while len(new_ask_order_prices) > 0:
            if sampling_df.loc[index]['askp0'] > new_ask_order_prices[-1]:
                ask_order_price_trading_intensity.append( [ 
                    ( sampling_df.loc[index]['Datetime'] - new_ask_order_datetimes[-1]) / 1000 ,
                    ( new_ask_order_prices[-1] - 0.5 * ( sampling_df.loc[ new_ask_order_indexes[-1] ]['bidp0'] 
                           + sampling_df.loc[ new_ask_order_indexes[-1] ]['askp0'] ) )
                ] )
                new_ask_order_indexes.pop()
                new_ask_order_datetimes.pop()
                new_ask_order_prices.pop()
            else:
                break
        
        if sampling_df.loc[index]['askp0'] < sampling_df.loc[index - 1]['askp0']:    
            new_ask_order_indexes.append( index )
            new_ask_order_datetimes.append( int( sampling_df.loc[index]['Datetime'] ) )
            new_ask_order_prices.append( sampling_df.loc[index]['askp0'] )
        
        # collect bid orders           
                
        while len(new_bid_order_prices) > 0:
            if sampling_df.loc[index]['bidp0'] < new_bid_order_prices[-1]:
                bid_order_price_trading_intensity.append( [
                    ( sampling_df.loc[index]['Datetime'] - new_bid_order_datetimes[-1] ) / 1000,
                    ( 0.5 * ( sampling_df.loc[ new_bid_order_indexes[-1] ]['bidp0'] 
                           + sampling_df.loc[ new_bid_order_indexes[-1] ]['askp0'] ) - new_bid_order_prices[-1])
                ] )
                new_bid_order_indexes.pop()
                new_bid_order_datetimes.pop()
                new_bid_order_prices.pop()
            else:
                break
        
        if sampling_df.loc[index]['bidp0'] > sampling_df.loc[index - 1]['bidp0']:        
            new_bid_order_indexes.append( index )
            new_bid_order_datetimes.append( int( sampling_df.loc[index]['Datetime'] ) )
            new_bid_order_prices.append( sampling_df.loc[index]['bidp0'] )
        
    delta = np.array( bid_order_price_trading_intensity + ask_order_price_trading_intensity) 
    delta_S = delta[:, 0].reshape(-1, 1)
    delta_t = np.log( delta[:, 1] )
        
    regr = LinearRegression()
    regr.fit(delta_S, delta_t)
    
    return regr.coef_

In [299]:
trading_intensity(1710470100000)

array([0.00199554])

In [300]:
trading_intensity(1710470160000)

array([0.00712576])

In [301]:
trading_intensity(1710470880000)

array([0.04552101])

In [302]:
kline_df = pd.read_csv('historical_ETHUSDT_kline_data.csv')

In [303]:
kline_df.iloc[0:70,:]

         Datetime     Open     High      Low    Close    Volume
0   1710470040000  3817.55  3820.92  3813.48  3816.80  4548.518
1   1710470040000  3817.55  3820.92  3813.48  3816.78  4560.994
2   1710470040000  3817.55  3820.92  3813.48  3816.32  4565.007
3   1710470040000  3817.55  3820.92  3813.48  3815.68  4586.762
4   1710470040000  3817.55  3820.92  3813.48  3815.28  4607.774
..            ...      ...      ...      ...      ...       ...
65  1710470040000  3817.55  3820.92  3812.30  3814.22  5491.840
66  1710470040000  3817.55  3820.92  3812.30  3814.21  5492.761
67  1710470040000  3817.55  3820.92  3812.30  3813.41  5499.479
68  1710470040000  3817.55  3820.92  3812.30  3813.42  5501.716
69  1710470040000  3817.55  3820.92  3812.30  3813.74  5514.190

[70 rows x 6 columns]

In [304]:
kline_df.iloc[70:251,:]

          Datetime     Open     High      Low    Close    Volume
70   1710470100000  3813.77  3814.12  3813.77  3814.12    15.695
71   1710470100000  3813.77  3814.12  3813.37  3813.37    45.469
72   1710470100000  3813.77  3814.12  3813.36  3813.36    48.093
73   1710470100000  3813.77  3814.12  3812.96  3812.96    59.243
74   1710470100000  3813.77  3814.12  3812.96  3812.96    66.310
..             ...      ...      ...      ...      ...       ...
246  1710470100000  3813.77  3817.54  3811.82  3812.33  4377.398
247  1710470100000  3813.77  3817.54  3811.82  3812.34  4387.639
248  1710470100000  3813.77  3817.54  3811.82  3812.33  4389.458
249  1710470100000  3813.77  3817.54  3811.82  3812.16  4410.927
250  1710470100000  3813.77  3817.54  3811.82  3812.16  4410.927

[181 rows x 6 columns]

In [305]:
kline_df.iloc[251:451,:]

          Datetime     Open     High      Low    Close    Volume
251  1710470160000  3812.15  3812.15  3811.84  3811.84     2.179
252  1710470160000  3812.15  3812.15  3811.49  3811.49    16.610
253  1710470160000  3812.15  3812.15  3811.49  3811.50    32.073
254  1710470160000  3812.15  3812.15  3810.76  3810.76    53.764
255  1710470160000  3812.15  3812.15  3810.76  3810.77    61.677
..             ...      ...      ...      ...      ...       ...
446  1710470160000  3812.15  3814.04  3801.01  3801.81  6216.097
447  1710470160000  3812.15  3814.04  3801.01  3801.61  6220.260
448  1710470160000  3812.15  3814.04  3801.01  3801.62  6222.070
449  1710470160000  3812.15  3814.04  3801.01  3801.54  6237.016
450  1710470160000  3812.15  3814.04  3801.00  3801.31  6366.543

[200 rows x 6 columns]

In [306]:
kline_df.iloc[452:657,:]

          Datetime     Open     High      Low    Close     Volume
452  1710470220000  3801.31  3802.27  3801.31  3801.66     35.973
453  1710470220000  3801.31  3802.34  3801.31  3802.13    133.257
454  1710470220000  3801.31  3802.34  3801.31  3801.79    141.684
455  1710470220000  3801.31  3802.34  3801.31  3802.33    155.209
456  1710470220000  3801.31  3802.79  3801.31  3802.79    172.299
..             ...      ...      ...      ...      ...        ...
652  1710470220000  3801.31  3810.11  3794.64  3794.65  14211.083
653  1710470220000  3801.31  3810.11  3794.60  3794.87  14318.513
654  1710470220000  3801.31  3810.11  3794.07  3794.08  14391.767
655  1710470220000  3801.31  3810.11  3794.07  3794.08  14397.385
656  1710470220000  3801.31  3810.11  3794.07  3794.07  14398.090

[205 rows x 6 columns]

In [307]:
# Instant Volatility
# https://github.com/hummingbot/hummingbot/blob/master/hummingbot/strategy/__utils__/trailing_indicators/instant_volatility.py

def volatility(time):
    sampling_buffer = kline_df[kline_df['Datetime'] == time]['Close'].to_numpy()
    vol = np.sqrt(np.sum(np.square(np.diff( sampling_buffer ))) / sampling_buffer.size)
    return vol

In [308]:
volatility(1710470100000)

0.4094909924872539

In [309]:
volatility(1710470160000)

0.4103845757335497

In [310]:
volatility(1710470220000)

0.512193822763709

In [311]:
volatility(1710470280000)

0.506856811881999